//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStock
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
